export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_LOADER = 'APP/SHOW_LOADER'

export const HIDE_ALERT = 'APP/HIDE_ALERT'
export const SHOW_ALERT = 'APP/SHOW_ALERT'


export const SHOW_RIDES = 'RIDES/SHOW_RIDES'


export const REQUESTED_SUCCEEDED_RIDES = 'RIDES/REQUESTED_SUCCEEDED_RIDES'
export const REQUESTED_RIDES = 'RIDES/REQUESTED_RIDES'
export const REQUESTED_FAILED_RIDES = 'RIDES/REQUESTED_FAILED_RIDES'
export const REQUESTED_SUCCEEDED_CLOSE_RIDES = 'RIDES/REQUESTED_SUCCEEDED_CLOSE_RIDES'
